modName=MageAddons
modID=mageaddons
modVersion=0.0.2

minecraftVersion=1.21.1
yarnMappings=1.21.1+build.3
loaderVersion=0.16.9
fabricVersion=0.102.0+1.21.1
fabricKotlinVersion=1.12.2+kotlin.2.0.20
clothConfigVersion=15.0.140

kotlin.code.style=official
org.gradle.caching=true
org.gradle.jvmargs=-Xmx2G
